   <?php

use Illuminate\Database\Seeder;
use Faker\Factory as Faker;

class AlumnoTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
  /*    $faker = Faker::create();
      DB::table('alumno')->insert([
      'nombres' => "Javier Eduardo",
      'apellidos' => "Castellar Bustillo",
      'tipo_documento' => "C.C",
      'numero_documento' => "465484949",
      'fecha_nacimiento' => "01/07/1989",
      'departamento' => "Bolivar",
      'municipio' =>  "Cartagena",
      'edad' => "26",
      'direccion_residencia' => "avenida siempre viva 123",
      'nombre_persona' => "Laura",
      'apellido_persona' => "Castellar",
      'parentesco' => "hermana",
      'nombre_padre' => "Javier",
      'apellido_padre' => "Castellar",
      'tipo_documentop' => "C.C",
      'numero_documentop' => "1128060687",
      'direccion_padre' => "avenida siempre viva 123",
      'tel_padre' => "6642707",
      'dir_trabajop' => "no tiene",
      'tel_trabajop' => "6642707",
      'nombre_madre' => "Zully",
      'apellido_madre' => "Bustillo",
      'tipo_documentom' => "C.C",
      'numero_documentom' => "1128060647",
      'direccion_madre' => "avenida siempre viva 123",
      'tel_madre' => "6642707",
      'dir_trabajom' => "no tiene",
      'tel_trabajom' => "6642707",
      'nombre_acudiente' => "Javier",
      'apellido_acudiente' => "Castelar Bustillo",
      'tipo_documentopa' => "C.C",
      'numero_documentoa' => "1128060627",
      'direccion_acudiente' => "avenida siempre viva 123",
      'tel_acudiente' => "6642707",
      'dir_trabajoa' => "no tiene",
      'tel_trabajoa' => "6642707",
      'nombre_emergencia' => "Cecilia",
      'apellido_emergencia' => "Castellar Bustillo",
      'direccion_emergencia' => "avenida siempreviva 123",
      'tel_emergencia' => "3173796062",
      'tel_trabajoe' => "3173796062",
      'fecha_matricula' => "22/04/2016",
      'convenio' => "ICBF",
      'modulo' => "Azul",
      'programa' => "Delfin",
      '_fisioterapia_' => "no",
      '_equinoterapia_' => "si",
      'talleres' => "no",
      '_fonoaudiologia_' => "si",
      '_psicologia_' => "no",
      'terapia_acuatica' => "si",
      'terapia_ocupacional' => "si",
      'created_at' => $faker->dateTime(),
      'updated_at' => $faker->dateTime(),
    ]);

    $faker = Faker::create();
    DB::table('alumno')->insert([
    'nombres' => "Cecilia Alejandra",
    'apellidos' => "Castellar Bustillo",
    'tipo_documento' => "C.C",
    'numero_documento' => "13234567899",
    'fecha_nacimiento' => "01/07/1989",
    'departamento' => "Bolivar",
    'municipio' =>  "Cartagena",
    'edad' => "26",
    'direccion_residencia' => "avenida siempre viva 123",
    'nombre_persona' => "Laura",
    'apellido_persona' => "Castellar",
    'parentesco' => "hermana",
    'nombre_padre' => "Javier",
    'apellido_padre' => "Castellar",
    'tipo_documentop' => "C.C",
    'numero_documentop' => "1128060687",
    'direccion_padre' => "avenida siempre viva 123",
    'tel_padre' => "6642707",
    'dir_trabajop' => "no tiene",
    'tel_trabajop' => "6642707",
    'nombre_madre' => "Zully",
    'apellido_madre' => "Bustillo",
    'tipo_documentom' => "C.C",
    'numero_documentom' => "1128060647",
    'direccion_madre' => "avenida siempre viva 123",
    'tel_madre' => "6642707",
    'dir_trabajom' => "no tiene",
    'tel_trabajom' => "6642707",
    'nombre_acudiente' => "Javier",
    'apellido_acudiente' => "Castelar Bustillo",
    'tipo_documentopa' => "C.C",
    'numero_documentoa' => "1128060627",
    'direccion_acudiente' => "avenida siempre viva 123",
    'tel_acudiente' => "6642707",
    'dir_trabajoa' => "no tiene",
    'tel_trabajoa' => "6642707",
    'nombre_emergencia' => "Javier Eduardo",
    'apellido_emergencia' => "Castellar Bustillo",
    'direccion_emergencia' => "avenida siempreviva 123",
    'tel_emergencia' => "3173796062",
    'tel_trabajoe' => "3173796062",
    'fecha_matricula' => "22/04/2016",
    'convenio' => "ICBF",
    'modulo' => "Azul",
    'programa' => "Delfin",
    '_fisioterapia_' => "no",
    '_equinoterapia_' => "si",
    'talleres' => "no",
    '_fonoaudiologia_' => "si",
    '_psicologia_' => "no",
    'terapia_acuatica' => "no",
    'terapia_ocupacional' => "si",
    'created_at' => $faker->dateTime(),
    'updated_at' => $faker->dateTime(),
  ]);

  $faker = Faker::create();
  DB::table('alumno')->insert([
  'nombres' => "Andrea Stefania",
  'apellidos' => "Vivero Castellar",
  'tipo_documento' => "C.C",
  'numero_documento' => "1357908642",
  'fecha_nacimiento' => "1990-11-15",
  'departamento' => "Bolivar",
  'municipio' =>  "Cartagena",
  'edad' => "26",
  'direccion_residencia' => "Manga",
  'nombre_persona' => "Cecilia",
  'apellido_persona' => "Arbelaez",
  'parentesco' => "Abuela",
  'nombre_padre' => "Jorge ",
  'apellido_padre' => "Vivero",
  'tipo_documentop' => "C.C",
  'numero_documentop' => "1234567890",
  'direccion_padre' => " Manga",
  'tel_padre' => "5555555",
  'dir_trabajop' => "Mamonal",
  'tel_trabajop' => "000000",
  'nombre_madre' => "Martha ",
  'apellido_madre' => "Castellar",
  'tipo_documentom' => "C.C",
  'numero_documentom' => "0987654321 ",
  'direccion_madre' => " Manga ",
  'tel_madre' => "5555555 ",
  'dir_trabajom' => "Mamonal",
  'tel_trabajom' => "0000000",
  'nombre_acudiente' => "Jorge",
  'apellido_acudiente' => "Vivero",
  'tipo_documentopa' => "C.C",
  'numero_documentoa' => "1234567890",
  'direccion_acudiente' => "Manga",
  'tel_acudiente' => "5555555",
  'dir_trabajoa' => "Mamonal",
  'tel_trabajoa' => "0000000",
  'nombre_emergencia' => "Cecilia",
  'apellido_emergencia' => "Arbelaez",
  'direccion_emergencia' => "Castillogrande",
  'tel_emergencia' => "11111111",
  'tel_trabajoe' => "22222222",
  'fecha_matricula' => "2016-05-14 ",
  'convenio' => "Particular",
  'modulo' => "Esmeralda",
  'programa' => "Delfin",
  '_fisioterapia_' => "no",
  '_equinoterapia_' => "si",
  'talleres' => "no",
  '_fonoaudiologia_' => "si",
  '_psicologia_' => "no",
  'terapia_acuatica' => "no",
  'terapia_ocupacional' => "si",
  'created_at' => $faker->dateTime(),
  'updated_at' => $faker->dateTime(),
]);

$faker = Faker::create();
DB::table('alumno')->insert([
'nombres' => "Juan Diego",
'apellidos' => "Alvis Cotes",
'tipo_documento' => "T.I",
'numero_documento' => "34567",
'fecha_nacimiento' => "2004-01-15",
'departamento' => "Atlantico",
'municipio' =>  "Barranquilla",
'edad' => "12",
'direccion_residencia' => "Bosque",
'nombre_persona' => "Jorge",
'apellido_persona' => "Alvis",
'parentesco' => "Padre",
'nombre_padre' => "Jorge",
'apellido_padre' => "Alvis",
'tipo_documentop' => "C.C",
'numero_documentop' => "123456",
'direccion_padre' => "Bosque",
'tel_padre' => "3434343",
'dir_trabajop' => "Centro",
'tel_trabajop' => "00000000",
'nombre_madre' => "Maria",
'apellido_madre' => "Cotes",
'tipo_documentom' => "C.C",
'numero_documentom' => "67890",
'direccion_madre' => "Bosque",
'tel_madre' => "3434343",
'dir_trabajom' => "Centro",
'tel_trabajom' => "7777777",
'nombre_acudiente' => "Jorge",
'apellido_acudiente' => "Alvis",
'tipo_documentopa' => "C.C",
'numero_documentoa' => "123456",
'direccion_acudiente' => "Bosque",
'tel_acudiente' => "3434343",
'dir_trabajoa' => "Centro",
'tel_trabajoa' => "0000000",
'nombre_emergencia' => "Maria",
'apellido_emergencia' => "Cotes",
'direccion_emergencia' => "Bosque",
'tel_emergencia' => "3434343",
'tel_trabajoe' => "77777777",
'fecha_matricula' => "2016-03-10",
'convenio' => "Exito",
'modulo' => "Azul",
'programa' => "Estrella de mar",
'_fisioterapia_' => "no",
'_equinoterapia_' => "no",
'talleres' => "no",
'_fonoaudiologia_' => "no",
'_psicologia_' => "no",
'terapia_acuatica' => "no",
'terapia_ocupacional' => "si",
'created_at' => $faker->dateTime(),
'updated_at' => $faker->dateTime(),
]);*/
$faker = Faker::create();
     foreach(range(1,10) as $index) {
        DB::table('alumno')->insert([
        'nombres' => $faker->firstname,
        'apellidos' => $faker->lastname,
        'tipo_documento' => "T.I",
        'numero_documento' => $faker->unique()->ean13,
        'fecha_nacimiento' => $faker->date($format = 'Y-m-d', $max = 'now'),
        'departamento' => "Bolivar",
        'municipio' => "Cartagena",
        'edad' => "12",
        'direccion_residencia' => $faker->address,
        'nombre_persona' => $faker->firstname,
        'apellido_persona' => $faker->lastname,
        'parentesco' => "hermana",
        'nombre_padre' => $faker->firstname,
        'apellido_padre' => $faker->lastname,
        'tipo_documentop' => "C.C",
        'numero_documentop' => $faker->ean13,
        'direccion_padre' => $faker->address,
        'tel_padre' => $faker->phoneNumber,
        'dir_trabajop' => $faker->address,
        'tel_trabajop' => $faker->phoneNumber,
        'nombre_madre' => $faker->firstname,
        'apellido_madre' => $faker->lastname,
        'tipo_documentom' => "C.C",
        'numero_documentom' => $faker->ean13,
        'direccion_madre' => $faker->address,
        'tel_madre' => $faker->phoneNumber,
        'dir_trabajom' => $faker->address,
        'tel_trabajom' => $faker->phoneNumber,
        'nombre_acudiente' => $faker->firstname,
        'apellido_acudiente' => $faker->lastname,
        'tipo_documentopa' => "C.C",
        'numero_documentoa' => $faker->ean13,
        'direccion_acudiente' => $faker->address,
        'tel_acudiente' => $faker->phoneNumber,
        'dir_trabajoa' => $faker->address,
        'tel_trabajoa' => $faker->phoneNumber,
        'nombre_emergencia' => $faker->firstname,
        'apellido_emergencia' => $faker->lastname,
        'direccion_emergencia' => $faker->address,
        'tel_emergencia' => $faker->phoneNumber,
        'tel_trabajoe' => $faker->phoneNumber,
        'fecha_matricula' => $faker->date($format = 'Y-m-d', $max = 'now'),
        'convenio' => "ICBF",
        'modulo' => "Azul",
        'programa' => "Delfin",
        '_fisioterapia_' => "no",
        '_equinoterapia_' => "no",
        'talleres' => "no",
        '_fonoaudiologia_' => "no",
        '_psicologia_' => "no",
        'terapia_acuatica' => "no",
        'terapia_ocupacional' => "si",
        'created_at' => $faker->dateTime(),
        'updated_at' => $faker->dateTime()
      ]);
      }

      $faker = Faker::create();
           foreach(range(1,10) as $index) {
              DB::table('alumno')->insert([
              'nombres' => $faker->firstname,
              'apellidos' => $faker->lastname,
              'tipo_documento' => "T.I",
              'numero_documento' => $faker->unique()->ean13,
              'fecha_nacimiento' => $faker->date($format = 'Y-m-d', $max = 'now'),
              'departamento' => "Bolivar",
              'municipio' => "Cartagena",
              'edad' => "12",
              'direccion_residencia' => $faker->address,
              'nombre_persona' => $faker->firstname,
              'apellido_persona' => $faker->lastname,
              'parentesco' => "hermana",
              'nombre_padre' => $faker->firstname,
              'apellido_padre' => $faker->lastname,
              'tipo_documentop' => "C.C",
              'numero_documentop' => $faker->ean13,
              'direccion_padre' => $faker->address,
              'tel_padre' => $faker->phoneNumber,
              'dir_trabajop' => $faker->address,
              'tel_trabajop' => $faker->phoneNumber,
              'nombre_madre' => $faker->firstname,
              'apellido_madre' => $faker->lastname,
              'tipo_documentom' => "C.C",
              'numero_documentom' => $faker->ean13,
              'direccion_madre' => $faker->address,
              'tel_madre' => $faker->phoneNumber,
              'dir_trabajom' => $faker->address,
              'tel_trabajom' => $faker->phoneNumber,
              'nombre_acudiente' => $faker->firstname,
              'apellido_acudiente' => $faker->lastname,
              'tipo_documentopa' => "C.C",
              'numero_documentoa' => $faker->ean13,
              'direccion_acudiente' => $faker->address,
              'tel_acudiente' => $faker->phoneNumber,
              'dir_trabajoa' => $faker->address,
              'tel_trabajoa' => $faker->phoneNumber,
              'nombre_emergencia' => $faker->firstname,
              'apellido_emergencia' => $faker->lastname,
              'direccion_emergencia' => $faker->address,
              'tel_emergencia' => $faker->phoneNumber,
              'tel_trabajoe' => $faker->phoneNumber,
              'fecha_matricula' => $faker->date($format = 'Y-m-d', $max = 'now'),
              'convenio' => "Exito",
              'modulo' => "Esmeralda",
              'programa' => "Delfin",
              '_fisioterapia_' => "si",
              '_equinoterapia_' => "no",
              'talleres' => "no",
              '_fonoaudiologia_' => "no",
              '_psicologia_' => "si",
              'terapia_acuatica' => "si",
              'terapia_ocupacional' => "si",
              'created_at' => $faker->dateTime(),
              'updated_at' => $faker->dateTime()
            ]);
            }

            $faker = Faker::create();
                 foreach(range(1,10) as $index) {
                    DB::table('alumno')->insert([
                    'nombres' => $faker->firstname,
                    'apellidos' => $faker->lastname,
                    'tipo_documento' => "T.I",
                    'numero_documento' => $faker->unique()->ean13,
                    'fecha_nacimiento' => $faker->date($format = 'Y-m-d', $max = 'now'),
                    'departamento' => "Bolivar",
                    'municipio' => "Cartagena",
                    'edad' => "12",
                    'direccion_residencia' => $faker->address,
                    'nombre_persona' => $faker->firstname,
                    'apellido_persona' => $faker->lastname,
                    'parentesco' => "hermana",
                    'nombre_padre' => $faker->firstname,
                    'apellido_padre' => $faker->lastname,
                    'tipo_documentop' => "C.C",
                    'numero_documentop' => $faker->ean13,
                    'direccion_padre' => $faker->address,
                    'tel_padre' => $faker->phoneNumber,
                    'dir_trabajop' => $faker->address,
                    'tel_trabajop' => $faker->phoneNumber,
                    'nombre_madre' => $faker->firstname,
                    'apellido_madre' => $faker->lastname,
                    'tipo_documentom' => "C.C",
                    'numero_documentom' => $faker->ean13,
                    'direccion_madre' => $faker->address,
                    'tel_madre' => $faker->phoneNumber,
                    'dir_trabajom' => $faker->address,
                    'tel_trabajom' => $faker->phoneNumber,
                    'nombre_acudiente' => $faker->firstname,
                    'apellido_acudiente' => $faker->lastname,
                    'tipo_documentopa' => "C.C",
                    'numero_documentoa' => $faker->ean13,
                    'direccion_acudiente' => $faker->address,
                    'tel_acudiente' => $faker->phoneNumber,
                    'dir_trabajoa' => $faker->address,
                    'tel_trabajoa' => $faker->phoneNumber,
                    'nombre_emergencia' => $faker->firstname,
                    'apellido_emergencia' => $faker->lastname,
                    'direccion_emergencia' => $faker->address,
                    'tel_emergencia' => $faker->phoneNumber,
                    'tel_trabajoe' => $faker->phoneNumber,
                    'fecha_matricula' => $faker->date($format = 'Y-m-d', $max = 'now'),
                    'convenio' => "Ferrocarril",
                    'modulo' => "Rojo",
                    'programa' => "Colibri",
                    '_fisioterapia_' => "no",
                    '_equinoterapia_' => "no",
                    'talleres' => "no",
                    '_fonoaudiologia_' => "no",
                    '_psicologia_' => "no",
                    'terapia_acuatica' => "no",
                    'terapia_ocupacional' => "si",
                    'created_at' => $faker->dateTime(),
                    'updated_at' => $faker->dateTime()
                  ]);
                  }

                  $faker = Faker::create();
                       foreach(range(1,10) as $index) {
                          DB::table('alumno')->insert([
                          'nombres' => $faker->firstname,
                          'apellidos' => $faker->lastname,
                          'tipo_documento' => "T.I",
                          'numero_documento' => $faker->unique()->ean13,
                          'fecha_nacimiento' => $faker->date($format = 'Y-m-d', $max = 'now'),
                          'departamento' => "Bolivar",
                          'municipio' => "Cartagena",
                          'edad' => "12",
                          'direccion_residencia' => $faker->address,
                          'nombre_persona' => $faker->firstname,
                          'apellido_persona' => $faker->lastname,
                          'parentesco' => "hermana",
                          'nombre_padre' => $faker->firstname,
                          'apellido_padre' => $faker->lastname,
                          'tipo_documentop' => "C.C",
                          'numero_documentop' => $faker->ean13,
                          'direccion_padre' => $faker->address,
                          'tel_padre' => $faker->phoneNumber,
                          'dir_trabajop' => $faker->address,
                          'tel_trabajop' => $faker->phoneNumber,
                          'nombre_madre' => $faker->firstname,
                          'apellido_madre' => $faker->lastname,
                          'tipo_documentom' => "C.C",
                          'numero_documentom' => $faker->ean13,
                          'direccion_madre' => $faker->address,
                          'tel_madre' => $faker->phoneNumber,
                          'dir_trabajom' => $faker->address,
                          'tel_trabajom' => $faker->phoneNumber,
                          'nombre_acudiente' => $faker->firstname,
                          'apellido_acudiente' => $faker->lastname,
                          'tipo_documentopa' => "C.C",
                          'numero_documentoa' => $faker->ean13,
                          'direccion_acudiente' => $faker->address,
                          'tel_acudiente' => $faker->phoneNumber,
                          'dir_trabajoa' => $faker->address,
                          'tel_trabajoa' => $faker->phoneNumber,
                          'nombre_emergencia' => $faker->firstname,
                          'apellido_emergencia' => $faker->lastname,
                          'direccion_emergencia' => $faker->address,
                          'tel_emergencia' => $faker->phoneNumber,
                          'tel_trabajoe' => $faker->phoneNumber,
                          'fecha_matricula' => $faker->date($format = 'Y-m-d', $max = 'now'),
                          'convenio' => "ICBF",
                          'modulo' => "Japon",
                          'programa' => "Tigre",
                          '_fisioterapia_' => "si",
                          '_equinoterapia_' => "si",
                          'talleres' => "no",
                          '_fonoaudiologia_' => "no",
                          '_psicologia_' => "si",
                          'terapia_acuatica' => "no",
                          'terapia_ocupacional' => "no",
                          'created_at' => $faker->dateTime(),
                          'updated_at' => $faker->dateTime()
                        ]);
                        }
}
    }
